![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [116]:
# Import necessary packages
import pandas as pd
import numpy as np

In [117]:
# Load the CSV file
df_csv = pd.read_csv('data/airbnb_price.csv')

# Load the TSV file
df_tsv = pd.read_csv('data/airbnb_last_review.tsv', sep='\t')

# Load the Excel file
df_excel = pd.read_excel('data/airbnb_room_type.xlsx')

print('Done Loading')

Done Loading

In [118]:
# Display the first 5 rows of the df_csv DataFrame
df_csv.head(5)

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [119]:
# Display the first 5 rows of the df_tsv DataFrame
df_tsv.head(5)

   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [120]:
# Display the first 5 rows of the df_excel DataFrame
df_excel.head(5)

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt

In [121]:
# observing the datatypes and information
print(df_csv.info())
print(df_tsv.info())
print(df_excel.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None

In [122]:
# Merge df_csv and df_tsv DataFrames on the 'listing_id' column using an outer join
new_df = df_csv.merge(df_tsv, on='listing_id', how='outer')
new_df.head()

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 5 columns]

In [123]:
# Merge new_df and df_excel DataFrames on the 'listing_id' column using an outer join
airbnb_df = new_df.merge(df_excel, on  = 'listing_id', how = 'outer')
airbnb_df.head()

   listing_id  ...        room_type
0        2595  ...  Entire home/apt
1        3831  ...  Entire home/apt
2        5099  ...  Entire home/apt
3        5178  ...     private room
4        5238  ...  Entire home/apt

[5 rows x 7 columns]

In [124]:
# Convert the 'last_review' column to datetime format
airbnb_df['last_review'] = pd.to_datetime(airbnb_df['last_review'])

# Display information about the DataFrame to check datatypes and non-null counts
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
 3   host_name    25201 non-null  object
 4   last_review  25209 non-null  datetime64[ns]
 5   description  25199 non-null  object
 6   room_type    25209 non-null  object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 1.5+ MB

In [125]:
# Find the most recent and earliest review dates in the 'last_review' column
recent_review = airbnb_df['last_review'].max()
earliest_review = airbnb_df['last_review'].min()

In [126]:
# Display the most recent and earliest review dates
recent_review, earliest_review

(Timestamp('2019-07-09 00:00:00'), Timestamp('2019-01-01 00:00:00'))

In [127]:
airbnb_df['room_type'].value_counts()

Entire home/apt    8458
Private room       7241
entire home/apt    2665
private room       2248
ENTIRE HOME/APT    2143
PRIVATE ROOM       1867
Shared room         380
shared room         110
SHARED ROOM          97
Name: room_type, dtype: int64

In [128]:
# standardizing the room type column by changing every value to lower case
airbnb_df['room_type'] = airbnb_df['room_type'].str.lower()
airbnb_df['room_type'].value_counts()

entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [129]:
# Count the number of listings where the room type is 'private room'
private_room_count = airbnb_df[airbnb_df['room_type'] == 'private room'].shape[0]
private_room_count

11356

In [130]:
# Remove the string ' dollars' from the 'price' column and convert the column to float type
airbnb_df['price'] = airbnb_df['price'].str.replace(' dollars', '')
airbnb_df['price'] = airbnb_df['price'].astype('float')

In [131]:
airbnb_df.head()

   listing_id  ...        room_type
0        2595  ...  entire home/apt
1        3831  ...  entire home/apt
2        5099  ...  entire home/apt
3        5178  ...     private room
4        5238  ...  entire home/apt

[5 rows x 7 columns]

In [132]:
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  float64
 2   nbhood_full  25209 non-null  object
 3   host_name    25201 non-null  object
 4   last_review  25209 non-null  datetime64[ns]
 5   description  25199 non-null  object
 6   room_type    25209 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.5+ MB

In [133]:
# Calculate the average listing price from the 'price' column of airbnb_df
average_listing_price = airbnb_df['price'].mean()
# Display the average price rounded to the nearest integer
f'{average_listing_price:.0f}'

'142'

In [134]:
# Create a DataFrame summarizing review and listing statistics
review_dates = pd.DataFrame({
    'first_reviewed': [earliest_review],  # Earliest review date
    'last_reviewed': [recent_review],     # Most recent review date
    'nb_private_rooms': [private_room_count],  # Number of private room listings
    'avg_price': [round(average_listing_price, 2)]  # Average listing price, rounded to 2 decimals
})
review_dates

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78