![Two data scientists working on a dashboard.](hr-image-small.png)

A common problem when creating models to generate business value from data is that the datasets can be so large that it can take days for the model to generate predictions. Ensuring that your dataset is stored as efficiently as possible is crucial for allowing these models to run on a more reasonable timescale without having to reduce the size of the dataset.

You've been hired by a major online data science training provider called *Training Data Ltd.* to clean up one of their largest customer datasets. This dataset will eventually be used to predict whether their students are looking for a new job or not, information that they will then use to direct them to prospective recruiters.

You've been given access to `customer_train.csv`, which is a subset of their entire customer dataset, so you can create a proof-of-concept of a much more efficient storage solution. The dataset contains anonymized student information, and whether they were looking for a new job or not during training:

| Column                   | Description                                                                      |
|------------------------- |--------------------------------------------------------------------------------- |
| `student_id`             | A unique ID for each student.                                                    |
| `city`                   | A code for the city the student lives in.                                        |
| `city_development_index` | A scaled development index for the city.                                         |
| `gender`                 | The student's gender.                                                            |
| `relevant_experience`    | An indicator of the student's work relevant experience.                          |
| `enrolled_university`    | The type of university course enrolled in (if any).                              |
| `education_level`        | The student's education level.                                                   |
| `major_discipline`       | The educational discipline of the student.                                       |
| `experience`             | The student's total work experience (in years).                                  |
| `company_size`           | The number of employees at the student's current employer.                       |
| `company_type`           | The type of company employing the student.                                       |
| `last_new_job`           | The number of years between the student's current and previous jobs.             |
| `training_hours`         | The number of hours of training completed.                                       |
| `job_change`             | An indicator of whether the student is looking for a new job (`1`) or not (`0`). |

In [120]:
# Import necessary libraries
import pandas as pd

# Load the dataset
ds_jobs = pd.read_csv("customer_train.csv")

# View the dataset
ds_jobs.head()

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36        1.0
1       29725   city_40  ...              47        0.0
2       11561   city_21  ...              83        0.0
3       33241  city_115  ...              52        1.0
4         666  city_162  ...               8        0.0

[5 rows x 14 columns]

In [121]:
# Create a copy of ds_jobs for transforming
ds_jobs_transformed = ds_jobs.copy()

ds_jobs_transformed.head(5)

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36        1.0
1       29725   city_40  ...              47        0.0
2       11561   city_21  ...              83        0.0
3       33241  city_115  ...              52        1.0
4         666  city_162  ...               8        0.0

[5 rows x 14 columns]

In [122]:
# inspect the datatype of the dataset

ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [123]:
# Display column names and their data types
ds_jobs_transformed.info()

# Display the first few rows to understand the contents of each column
ds_jobs_transformed.head()

# For each column, display the number of unique values and the most common values
for col in ds_jobs_transformed.columns:
    print(f"\nColumn: {col}")
    print(f"Data type: {ds_jobs_transformed[col].dtype}")
    print(f"Number of unique values: {ds_jobs_transformed[col].nunique()}")
    print(ds_jobs_transformed[col].value_counts(dropna=False).head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

Column: student_id
Data type: int64
Number of unique values: 19158
8949     1
10660    1
30726    1
18507    1
31273    1
16098    1
27022    1
4872     1
20007    1
14983    1
Name: student_id, dtype: int64

Column: city
Data type: object
Number of unique values: 123
city_103    4355
city_21     2702
city_16     1533
city_114    1336
city_160     845
city_136     586
city_67      431
city_75      305
city_102     304
city_104     301
Name: city, dtype: int64

Column: city_development_index
Data type: float64
Number of unique values: 93
0.920    5200
0.624    2702
0.910    1533
0.926    1336
0.698     683
0.897     586
0.939     497
0.855     431
0.804     304
0.924     301
Name: city_development_index, dtype: int64

Column: gender
Data type: object
Number of unique values: 3
Male      13221
NaN        4508
Female     1238
Other       191
Name: gender, dtype: int64

Column: relevant_experience
Data type: object
Number of unique values: 2
Has relevant experience    13792
No relevant experience      5366
Name: relevant_experience, dtype: int64

Column: enrolled_university
Data type: object
Number of unique values: 3
no_enrollment       13817
Full time course     3757
Part time course     1198
NaN                   386
Name: enrolled_university, dtype: int64

Column: education_level
Data type: object
Number of unique values: 5
Graduate          11598
Masters            4361
High School        2017
NaN                 460
Phd                 414
Primary School      308
Name: education_level, dtype: int64

Column: major_discipline
Data type: object
Number of unique values: 6
STEM               14492
NaN                 2813
Humanities           669
Other                381
Business Degree      327
Arts                 253
No Major             223
Name: major_discipline, dtype: int64

Column: experience
Data type: object
Number of unique values: 22
>20    3286
5      1430
4      1403
3      1354
6      1216
2      1127
7      1028
10      985
9       980
8       802
Name: experience, dtype: int64

Column: company_size
Data type: object
Number of unique values: 8
NaN          5938
50-99        3083
100-499      2571
10000+       2019
10-49        1471
1000-4999    1328
<10          1308
500-999       877
5000-9999     563
Name: company_size, dtype: int64

Column: company_type
Data type: object
Number of unique values: 6
Pvt Ltd                9817
NaN                    6140
Funded Startup         1001
Public Sector           955
Early Stage Startup     603
NGO                     521
Other                   121
Name: company_type, dtype: int64

Column: last_new_job
Data type: object
Number of unique values: 6
1        8040
>4       3290
2        2900
never    2452
4        1029
3        1024
NaN       423
Name: last_new_job, dtype: int64

Column: training_hours
Data type: int64
Number of unique values: 241
28    329
12    292
18    291
22    282
50    279
20    278
24    273
17    273
6     261
34    261
Name: training_hours, dtype: int64

Column: job_change
Data type: float64
Number of unique values: 2
0.0    14381
1.0     4777
Name: job_change, dtype: int64

In [124]:
# Ensure 'student_id' and 'training_hours' columns are of type int32
ds_jobs_transformed[['student_id', 'training_hours']] = ds_jobs_transformed[['student_id', 'training_hours']].astype('int32')

# Display the dataframe info to confirm the changes
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  float64
dtypes: float64(2), int32(2), object(10)
memory usage: 1.9+ MB

In [125]:
# Convert 'city_development_index' and 'job_change' columns to float16 data type
ds_jobs_transformed[['city_development_index', 'job_change']] = ds_jobs_transformed[['city_development_index', 'job_change']].astype('float16')

# Display the dataframe info to confirm the changes
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  float16
dtypes: float16(2), int32(2), object(10)
memory usage: 1.7+ MB

In [126]:
# Identify columns with only two unique values (excluding NaN)
cols_with_two_factors = [
    col for col in ds_jobs_transformed.columns
    if ds_jobs_transformed[col].nunique(dropna=True) == 2
]

# Convert these columns to boolean type
for col in cols_with_two_factors:
    # If the column is already boolean, skip
    if ds_jobs_transformed[col].dtype == 'bool':
        continue
    # Map the two unique values to True/False
    unique_vals = ds_jobs_transformed[col].dropna().unique()
    mapping = {unique_vals[0]: True, unique_vals[1]: False}
    ds_jobs_transformed[col] = ds_jobs_transformed[col].map(mapping)

ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), float16(1), int32(2), object(9)
memory usage: 1.5+ MB

In [127]:
# Define the order for 'enrolled_university'
enrolled_university_order = [
    "no_enrollment", "Part time course", "Full time course"
]

# Nominal categorical columns (remove 'enrolled_university')
nominal_cols = [
    "city",
    "gender",
    "major_discipline",
    "company_type"
]

# Ordinal categorical columns and their order (add 'enrolled_university')
ordinal_categories = {
    "enrolled_university": enrolled_university_order,
    "education_level": [
        "Primary School", "High School", "Graduate", "Masters", "Phd"
    ],
    "company_size": [
        "<10", "10/49", "50-99", "100-500", "500-999", "1000-4999", "5000-9999", "10000+"
    ],
    "experience": [
        "<1", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", ">20"
    ],
    "last_new_job": [
        "never", "1", "2", "3", "4", ">4"
    ]
}

# Convert nominal columns to 'category' dtype
for col in nominal_cols:
    ds_jobs_transformed[col] = ds_jobs_transformed[col].astype("category")

# Convert ordinal columns to ordered 'category' dtype
for col, order in ordinal_categories.items():
    ds_jobs_transformed[col] = pd.Categorical(
        ds_jobs_transformed[col],
        categories=order,
        ordered=True
    )

ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  category
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  category
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  category
 6   education_level         18698 non-null  category
 7   major_discipline        16345 non-null  category
 8   experience              19093 non-null  category
 9   company_size            9178 non-null   category
 10  company_type            13018 non-null  category
 11  last_new_job            18735 non-null  category
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 400.2 KB

In [128]:
# Filter students with 10 or more years experience at companies with at least 1000 employees
ds_jobs_transformed = ds_jobs_transformed[(ds_jobs_transformed['experience'] >= '10') & (ds_jobs_transformed['company_size'] >= '1000-4999')]
ds_jobs_transformed.head(5)

    student_id      city  ...  training_hours job_change
9          699  city_103  ...             123      False
12       25619   city_61  ...              23      False
31       22293  city_103  ...             141      False
34       26494   city_16  ...             145      False
40        2547  city_114  ...              14      False

[5 rows x 14 columns]

In [129]:
# compare original dataframe and transformed dataframe
print(ds_jobs.info())
print(ds_jobs_transformed.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2201 entries, 9 to 19143
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              2201 non-null   int32
 1   city                    2201 non-null   category
 2   city_development_index  2201 non-null   float16
 3   gender                  1821 non-null   category
 4   relevant_experience     2201 non-null   bool
 5   enrolled_university     2185 non-null   category
 6   education_level         2184 non-null   category
 7   major_discipline        2097 non-null   category
 8   experience              2201 non-null   category
 9   company_size            2201 non-null   category
 10  company_type            2144 non-null   category
 11  last_new_job            2184 non-null   category
 12  training_hours          2201 non-null   int32
 13  job_change              2201 non-null   bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 69.5 KB
None